// Code generated by ent, DO NOT EDIT.

package setting

import (
	"entgo.io/ent/dialect/sql"
	"github.com/ankushx05/authentication/internal/platform/database/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Setting {
	return predicate.Setting(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Setting {
	return predicate.Setting(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Setting {
	return predicate.Setting(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Setting {
	return predicate.Setting(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Setting {
	return predicate.Setting(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Setting {
	return predicate.Setting(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Setting {
	return predicate.Setting(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Setting {
	return predicate.Setting(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Setting {
	return predicate.Setting(sql.FieldLTE(FieldID, id))
}

// UniqueID applies equality check predicate on the "unique_id" field. It's identical to UniqueIDEQ.
func UniqueID(v string) predicate.Setting {
	return predicate.Setting(sql.FieldEQ(FieldUniqueID, v))
}

// MailIsNil applies the IsNil predicate on the "mail" field.
func MailIsNil() predicate.Setting {
	return predicate.Setting(sql.FieldIsNull(FieldMail))
}

// MailNotNil applies the NotNil predicate on the "mail" field.
func MailNotNil() predicate.Setting {
	return predicate.Setting(sql.FieldNotNull(FieldMail))
}

// UniqueIDEQ applies the EQ predicate on the "unique_id" field.
func UniqueIDEQ(v string) predicate.Setting {
	return predicate.Setting(sql.FieldEQ(FieldUniqueID, v))
}

// UniqueIDNEQ applies the NEQ predicate on the "unique_id" field.
func UniqueIDNEQ(v string) predicate.Setting {
	return predicate.Setting(sql.FieldNEQ(FieldUniqueID, v))
}

// UniqueIDIn applies the In predicate on the "unique_id" field.
func UniqueIDIn(vs ...string) predicate.Setting {
	return predicate.Setting(sql.FieldIn(FieldUniqueID, vs...))
}

// UniqueIDNotIn applies the NotIn predicate on the "unique_id" field.
func UniqueIDNotIn(vs ...string) predicate.Setting {
	return predicate.Setting(sql.FieldNotIn(FieldUniqueID, vs...))
}

// UniqueIDGT applies the GT predicate on the "unique_id" field.
func UniqueIDGT(v string) predicate.Setting {
	return predicate.Setting(sql.FieldGT(FieldUniqueID, v))
}

// UniqueIDGTE applies the GTE predicate on the "unique_id" field.
func UniqueIDGTE(v string) predicate.Setting {
	return predicate.Setting(sql.FieldGTE(FieldUniqueID, v))
}

// UniqueIDLT applies the LT predicate on the "unique_id" field.
func UniqueIDLT(v string) predicate.Setting {
	return predicate.Setting(sql.FieldLT(FieldUniqueID, v))
}

// UniqueIDLTE applies the LTE predicate on the "unique_id" field.
func UniqueIDLTE(v string) predicate.Setting {
	return predicate.Setting(sql.FieldLTE(FieldUniqueID, v))
}

// UniqueIDContains applies the Contains predicate on the "unique_id" field.
func UniqueIDContains(v string) predicate.Setting {
	return predicate.Setting(sql.FieldContains(FieldUniqueID, v))
}

// UniqueIDHasPrefix applies the HasPrefix predicate on the "unique_id" field.
func UniqueIDHasPrefix(v string) predicate.Setting {
	return predicate.Setting(sql.FieldHasPrefix(FieldUniqueID, v))
}

// UniqueIDHasSuffix applies the HasSuffix predicate on the "unique_id" field.
func UniqueIDHasSuffix(v string) predicate.Setting {
	return predicate.Setting(sql.FieldHasSuffix(FieldUniqueID, v))
}

// UniqueIDEqualFold applies the EqualFold predicate on the "unique_id" field.
func UniqueIDEqualFold(v string) predicate.Setting {
	return predicate.Setting(sql.FieldEqualFold(FieldUniqueID, v))
}

// UniqueIDContainsFold applies the ContainsFold predicate on the "unique_id" field.
func UniqueIDContainsFold(v string) predicate.Setting {
	return predicate.Setting(sql.FieldContainsFold(FieldUniqueID, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Setting) predicate.Setting {
	return predicate.Setting(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Setting) predicate.Setting {
	return predicate.Setting(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Setting) predicate.Setting {
	return predicate.Setting(sql.NotPredicates(p))
}
