// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ankushx05/authentication/internal/platform/database/ent/mailtemplates"
	"github.com/google/uuid"
)

// MailTemplatesCreate is the builder for creating a MailTemplates entity.
type MailTemplatesCreate struct {
	config
	mutation *MailTemplatesMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *MailTemplatesCreate) SetCreatedAt(v time.Time) *MailTemplatesCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *MailTemplatesCreate) SetNillableCreatedAt(v *time.Time) *MailTemplatesCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *MailTemplatesCreate) SetUpdatedAt(v time.Time) *MailTemplatesCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *MailTemplatesCreate) SetNillableUpdatedAt(v *time.Time) *MailTemplatesCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *MailTemplatesCreate) SetDeletedAt(v time.Time) *MailTemplatesCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *MailTemplatesCreate) SetNillableDeletedAt(v *time.Time) *MailTemplatesCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *MailTemplatesCreate) SetName(v string) *MailTemplatesCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetSubject sets the "subject" field.
func (_c *MailTemplatesCreate) SetSubject(v string) *MailTemplatesCreate {
	_c.mutation.SetSubject(v)
	return _c
}

// SetBody sets the "body" field.
func (_c *MailTemplatesCreate) SetBody(v string) *MailTemplatesCreate {
	_c.mutation.SetBody(v)
	return _c
}

// SetVariables sets the "variables" field.
func (_c *MailTemplatesCreate) SetVariables(v []string) *MailTemplatesCreate {
	_c.mutation.SetVariables(v)
	return _c
}

// SetUniqueKey sets the "unique_key" field.
func (_c *MailTemplatesCreate) SetUniqueKey(v string) *MailTemplatesCreate {
	_c.mutation.SetUniqueKey(v)
	return _c
}

// SetID sets the "id" field.
func (_c *MailTemplatesCreate) SetID(v uuid.UUID) *MailTemplatesCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *MailTemplatesCreate) SetNillableID(v *uuid.UUID) *MailTemplatesCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the MailTemplatesMutation object of the builder.
func (_c *MailTemplatesCreate) Mutation() *MailTemplatesMutation {
	return _c.mutation
}

// Save creates the MailTemplates in the database.
func (_c *MailTemplatesCreate) Save(ctx context.Context) (*MailTemplates, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *MailTemplatesCreate) SaveX(ctx context.Context) *MailTemplates {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MailTemplatesCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MailTemplatesCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *MailTemplatesCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := mailtemplates.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := mailtemplates.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := mailtemplates.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *MailTemplatesCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "MailTemplates.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "MailTemplates.updated_at"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "MailTemplates.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := mailtemplates.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "MailTemplates.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Subject(); !ok {
		return &ValidationError{Name: "subject", err: errors.New(`ent: missing required field "MailTemplates.subject"`)}
	}
	if v, ok := _c.mutation.Subject(); ok {
		if err := mailtemplates.SubjectValidator(v); err != nil {
			return &ValidationError{Name: "subject", err: fmt.Errorf(`ent: validator failed for field "MailTemplates.subject": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Body(); !ok {
		return &ValidationError{Name: "body", err: errors.New(`ent: missing required field "MailTemplates.body"`)}
	}
	if v, ok := _c.mutation.Body(); ok {
		if err := mailtemplates.BodyValidator(v); err != nil {
			return &ValidationError{Name: "body", err: fmt.Errorf(`ent: validator failed for field "MailTemplates.body": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UniqueKey(); !ok {
		return &ValidationError{Name: "unique_key", err: errors.New(`ent: missing required field "MailTemplates.unique_key"`)}
	}
	if v, ok := _c.mutation.UniqueKey(); ok {
		if err := mailtemplates.UniqueKeyValidator(v); err != nil {
			return &ValidationError{Name: "unique_key", err: fmt.Errorf(`ent: validator failed for field "MailTemplates.unique_key": %w`, err)}
		}
	}
	return nil
}

func (_c *MailTemplatesCreate) sqlSave(ctx context.Context) (*MailTemplates, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *MailTemplatesCreate) createSpec() (*MailTemplates, *sqlgraph.CreateSpec) {
	var (
		_node = &MailTemplates{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(mailtemplates.Table, sqlgraph.NewFieldSpec(mailtemplates.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(mailtemplates.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(mailtemplates.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(mailtemplates.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(mailtemplates.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Subject(); ok {
		_spec.SetField(mailtemplates.FieldSubject, field.TypeString, value)
		_node.Subject = value
	}
	if value, ok := _c.mutation.Body(); ok {
		_spec.SetField(mailtemplates.FieldBody, field.TypeString, value)
		_node.Body = value
	}
	if value, ok := _c.mutation.Variables(); ok {
		_spec.SetField(mailtemplates.FieldVariables, field.TypeJSON, value)
		_node.Variables = value
	}
	if value, ok := _c.mutation.UniqueKey(); ok {
		_spec.SetField(mailtemplates.FieldUniqueKey, field.TypeString, value)
		_node.UniqueKey = value
	}
	return _node, _spec
}

// MailTemplatesCreateBulk is the builder for creating many MailTemplates entities in bulk.
type MailTemplatesCreateBulk struct {
	config
	err      error
	builders []*MailTemplatesCreate
}

// Save creates the MailTemplates entities in the database.
func (_c *MailTemplatesCreateBulk) Save(ctx context.Context) ([]*MailTemplates, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*MailTemplates, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MailTemplatesMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *MailTemplatesCreateBulk) SaveX(ctx context.Context) []*MailTemplates {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MailTemplatesCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MailTemplatesCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
