// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ankushx05/authentication/internal/platform/database/ent/mailtemplates"
	"github.com/ankushx05/authentication/internal/platform/database/ent/predicate"
)

// MailTemplatesDelete is the builder for deleting a MailTemplates entity.
type MailTemplatesDelete struct {
	config
	hooks    []Hook
	mutation *MailTemplatesMutation
}

// Where appends a list predicates to the MailTemplatesDelete builder.
func (_d *MailTemplatesDelete) Where(ps ...predicate.MailTemplates) *MailTemplatesDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *MailTemplatesDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *MailTemplatesDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *MailTemplatesDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(mailtemplates.Table, sqlgraph.NewFieldSpec(mailtemplates.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// MailTemplatesDeleteOne is the builder for deleting a single MailTemplates entity.
type MailTemplatesDeleteOne struct {
	_d *MailTemplatesDelete
}

// Where appends a list predicates to the MailTemplatesDelete builder.
func (_d *MailTemplatesDeleteOne) Where(ps ...predicate.MailTemplates) *MailTemplatesDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *MailTemplatesDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{mailtemplates.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *MailTemplatesDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
