// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/ankushx05/authentication/internal/platform/database/ent/mailtemplates"
	"github.com/ankushx05/authentication/internal/platform/database/ent/predicate"
)

// MailTemplatesUpdate is the builder for updating MailTemplates entities.
type MailTemplatesUpdate struct {
	config
	hooks    []Hook
	mutation *MailTemplatesMutation
}

// Where appends a list predicates to the MailTemplatesUpdate builder.
func (_u *MailTemplatesUpdate) Where(ps ...predicate.MailTemplates) *MailTemplatesUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *MailTemplatesUpdate) SetUpdatedAt(v time.Time) *MailTemplatesUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *MailTemplatesUpdate) SetDeletedAt(v time.Time) *MailTemplatesUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *MailTemplatesUpdate) SetNillableDeletedAt(v *time.Time) *MailTemplatesUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *MailTemplatesUpdate) ClearDeletedAt() *MailTemplatesUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetName sets the "name" field.
func (_u *MailTemplatesUpdate) SetName(v string) *MailTemplatesUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *MailTemplatesUpdate) SetNillableName(v *string) *MailTemplatesUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetSubject sets the "subject" field.
func (_u *MailTemplatesUpdate) SetSubject(v string) *MailTemplatesUpdate {
	_u.mutation.SetSubject(v)
	return _u
}

// SetNillableSubject sets the "subject" field if the given value is not nil.
func (_u *MailTemplatesUpdate) SetNillableSubject(v *string) *MailTemplatesUpdate {
	if v != nil {
		_u.SetSubject(*v)
	}
	return _u
}

// SetBody sets the "body" field.
func (_u *MailTemplatesUpdate) SetBody(v string) *MailTemplatesUpdate {
	_u.mutation.SetBody(v)
	return _u
}

// SetNillableBody sets the "body" field if the given value is not nil.
func (_u *MailTemplatesUpdate) SetNillableBody(v *string) *MailTemplatesUpdate {
	if v != nil {
		_u.SetBody(*v)
	}
	return _u
}

// SetVariables sets the "variables" field.
func (_u *MailTemplatesUpdate) SetVariables(v []string) *MailTemplatesUpdate {
	_u.mutation.SetVariables(v)
	return _u
}

// AppendVariables appends value to the "variables" field.
func (_u *MailTemplatesUpdate) AppendVariables(v []string) *MailTemplatesUpdate {
	_u.mutation.AppendVariables(v)
	return _u
}

// ClearVariables clears the value of the "variables" field.
func (_u *MailTemplatesUpdate) ClearVariables() *MailTemplatesUpdate {
	_u.mutation.ClearVariables()
	return _u
}

// SetUniqueKey sets the "unique_key" field.
func (_u *MailTemplatesUpdate) SetUniqueKey(v string) *MailTemplatesUpdate {
	_u.mutation.SetUniqueKey(v)
	return _u
}

// SetNillableUniqueKey sets the "unique_key" field if the given value is not nil.
func (_u *MailTemplatesUpdate) SetNillableUniqueKey(v *string) *MailTemplatesUpdate {
	if v != nil {
		_u.SetUniqueKey(*v)
	}
	return _u
}

// Mutation returns the MailTemplatesMutation object of the builder.
func (_u *MailTemplatesUpdate) Mutation() *MailTemplatesMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *MailTemplatesUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MailTemplatesUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *MailTemplatesUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MailTemplatesUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *MailTemplatesUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := mailtemplates.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MailTemplatesUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := mailtemplates.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "MailTemplates.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Subject(); ok {
		if err := mailtemplates.SubjectValidator(v); err != nil {
			return &ValidationError{Name: "subject", err: fmt.Errorf(`ent: validator failed for field "MailTemplates.subject": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Body(); ok {
		if err := mailtemplates.BodyValidator(v); err != nil {
			return &ValidationError{Name: "body", err: fmt.Errorf(`ent: validator failed for field "MailTemplates.body": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UniqueKey(); ok {
		if err := mailtemplates.UniqueKeyValidator(v); err != nil {
			return &ValidationError{Name: "unique_key", err: fmt.Errorf(`ent: validator failed for field "MailTemplates.unique_key": %w`, err)}
		}
	}
	return nil
}

func (_u *MailTemplatesUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(mailtemplates.Table, mailtemplates.Columns, sqlgraph.NewFieldSpec(mailtemplates.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(mailtemplates.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(mailtemplates.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(mailtemplates.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(mailtemplates.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Subject(); ok {
		_spec.SetField(mailtemplates.FieldSubject, field.TypeString, value)
	}
	if value, ok := _u.mutation.Body(); ok {
		_spec.SetField(mailtemplates.FieldBody, field.TypeString, value)
	}
	if value, ok := _u.mutation.Variables(); ok {
		_spec.SetField(mailtemplates.FieldVariables, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedVariables(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, mailtemplates.FieldVariables, value)
		})
	}
	if _u.mutation.VariablesCleared() {
		_spec.ClearField(mailtemplates.FieldVariables, field.TypeJSON)
	}
	if value, ok := _u.mutation.UniqueKey(); ok {
		_spec.SetField(mailtemplates.FieldUniqueKey, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{mailtemplates.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// MailTemplatesUpdateOne is the builder for updating a single MailTemplates entity.
type MailTemplatesUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MailTemplatesMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *MailTemplatesUpdateOne) SetUpdatedAt(v time.Time) *MailTemplatesUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *MailTemplatesUpdateOne) SetDeletedAt(v time.Time) *MailTemplatesUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *MailTemplatesUpdateOne) SetNillableDeletedAt(v *time.Time) *MailTemplatesUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *MailTemplatesUpdateOne) ClearDeletedAt() *MailTemplatesUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetName sets the "name" field.
func (_u *MailTemplatesUpdateOne) SetName(v string) *MailTemplatesUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *MailTemplatesUpdateOne) SetNillableName(v *string) *MailTemplatesUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetSubject sets the "subject" field.
func (_u *MailTemplatesUpdateOne) SetSubject(v string) *MailTemplatesUpdateOne {
	_u.mutation.SetSubject(v)
	return _u
}

// SetNillableSubject sets the "subject" field if the given value is not nil.
func (_u *MailTemplatesUpdateOne) SetNillableSubject(v *string) *MailTemplatesUpdateOne {
	if v != nil {
		_u.SetSubject(*v)
	}
	return _u
}

// SetBody sets the "body" field.
func (_u *MailTemplatesUpdateOne) SetBody(v string) *MailTemplatesUpdateOne {
	_u.mutation.SetBody(v)
	return _u
}

// SetNillableBody sets the "body" field if the given value is not nil.
func (_u *MailTemplatesUpdateOne) SetNillableBody(v *string) *MailTemplatesUpdateOne {
	if v != nil {
		_u.SetBody(*v)
	}
	return _u
}

// SetVariables sets the "variables" field.
func (_u *MailTemplatesUpdateOne) SetVariables(v []string) *MailTemplatesUpdateOne {
	_u.mutation.SetVariables(v)
	return _u
}

// AppendVariables appends value to the "variables" field.
func (_u *MailTemplatesUpdateOne) AppendVariables(v []string) *MailTemplatesUpdateOne {
	_u.mutation.AppendVariables(v)
	return _u
}

// ClearVariables clears the value of the "variables" field.
func (_u *MailTemplatesUpdateOne) ClearVariables() *MailTemplatesUpdateOne {
	_u.mutation.ClearVariables()
	return _u
}

// SetUniqueKey sets the "unique_key" field.
func (_u *MailTemplatesUpdateOne) SetUniqueKey(v string) *MailTemplatesUpdateOne {
	_u.mutation.SetUniqueKey(v)
	return _u
}

// SetNillableUniqueKey sets the "unique_key" field if the given value is not nil.
func (_u *MailTemplatesUpdateOne) SetNillableUniqueKey(v *string) *MailTemplatesUpdateOne {
	if v != nil {
		_u.SetUniqueKey(*v)
	}
	return _u
}

// Mutation returns the MailTemplatesMutation object of the builder.
func (_u *MailTemplatesUpdateOne) Mutation() *MailTemplatesMutation {
	return _u.mutation
}

// Where appends a list predicates to the MailTemplatesUpdate builder.
func (_u *MailTemplatesUpdateOne) Where(ps ...predicate.MailTemplates) *MailTemplatesUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *MailTemplatesUpdateOne) Select(field string, fields ...string) *MailTemplatesUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated MailTemplates entity.
func (_u *MailTemplatesUpdateOne) Save(ctx context.Context) (*MailTemplates, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MailTemplatesUpdateOne) SaveX(ctx context.Context) *MailTemplates {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *MailTemplatesUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MailTemplatesUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *MailTemplatesUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := mailtemplates.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MailTemplatesUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := mailtemplates.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "MailTemplates.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Subject(); ok {
		if err := mailtemplates.SubjectValidator(v); err != nil {
			return &ValidationError{Name: "subject", err: fmt.Errorf(`ent: validator failed for field "MailTemplates.subject": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Body(); ok {
		if err := mailtemplates.BodyValidator(v); err != nil {
			return &ValidationError{Name: "body", err: fmt.Errorf(`ent: validator failed for field "MailTemplates.body": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UniqueKey(); ok {
		if err := mailtemplates.UniqueKeyValidator(v); err != nil {
			return &ValidationError{Name: "unique_key", err: fmt.Errorf(`ent: validator failed for field "MailTemplates.unique_key": %w`, err)}
		}
	}
	return nil
}

func (_u *MailTemplatesUpdateOne) sqlSave(ctx context.Context) (_node *MailTemplates, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(mailtemplates.Table, mailtemplates.Columns, sqlgraph.NewFieldSpec(mailtemplates.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "MailTemplates.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, mailtemplates.FieldID)
		for _, f := range fields {
			if !mailtemplates.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != mailtemplates.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(mailtemplates.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(mailtemplates.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(mailtemplates.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(mailtemplates.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Subject(); ok {
		_spec.SetField(mailtemplates.FieldSubject, field.TypeString, value)
	}
	if value, ok := _u.mutation.Body(); ok {
		_spec.SetField(mailtemplates.FieldBody, field.TypeString, value)
	}
	if value, ok := _u.mutation.Variables(); ok {
		_spec.SetField(mailtemplates.FieldVariables, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedVariables(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, mailtemplates.FieldVariables, value)
		})
	}
	if _u.mutation.VariablesCleared() {
		_spec.ClearField(mailtemplates.FieldVariables, field.TypeJSON)
	}
	if value, ok := _u.mutation.UniqueKey(); ok {
		_spec.SetField(mailtemplates.FieldUniqueKey, field.TypeString, value)
	}
	_node = &MailTemplates{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{mailtemplates.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
