// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// MailTemplates is the predicate function for mailtemplates builders.
type MailTemplates func(*sql.Selector)

// Setting is the predicate function for setting builders.
type Setting func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
