// Code generated by ent, DO NOT EDIT.

package mailtemplates

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/ankushx05/authentication/internal/platform/database/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.MailTemplates {
	return predicate.MailTemplates(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.MailTemplates {
	return predicate.MailTemplates(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.MailTemplates {
	return predicate.MailTemplates(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.MailTemplates {
	return predicate.MailTemplates(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.MailTemplates {
	return predicate.MailTemplates(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.MailTemplates {
	return predicate.MailTemplates(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.MailTemplates {
	return predicate.MailTemplates(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.MailTemplates {
	return predicate.MailTemplates(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.MailTemplates {
	return predicate.MailTemplates(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.MailTemplates {
	return predicate.MailTemplates(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.MailTemplates {
	return predicate.MailTemplates(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.MailTemplates {
	return predicate.MailTemplates(sql.FieldEQ(FieldDeletedAt, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.MailTemplates {
	return predicate.MailTemplates(sql.FieldEQ(FieldName, v))
}

// Subject applies equality check predicate on the "subject" field. It's identical to SubjectEQ.
func Subject(v string) predicate.MailTemplates {
	return predicate.MailTemplates(sql.FieldEQ(FieldSubject, v))
}

// Body applies equality check predicate on the "body" field. It's identical to BodyEQ.
func Body(v string) predicate.MailTemplates {
	return predicate.MailTemplates(sql.FieldEQ(FieldBody, v))
}

// UniqueKey applies equality check predicate on the "unique_key" field. It's identical to UniqueKeyEQ.
func UniqueKey(v string) predicate.MailTemplates {
	return predicate.MailTemplates(sql.FieldEQ(FieldUniqueKey, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.MailTemplates {
	return predicate.MailTemplates(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.MailTemplates {
	return predicate.MailTemplates(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.MailTemplates {
	return predicate.MailTemplates(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.MailTemplates {
	return predicate.MailTemplates(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.MailTemplates {
	return predicate.MailTemplates(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.MailTemplates {
	return predicate.MailTemplates(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.MailTemplates {
	return predicate.MailTemplates(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.MailTemplates {
	return predicate.MailTemplates(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.MailTemplates {
	return predicate.MailTemplates(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.MailTemplates {
	return predicate.MailTemplates(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.MailTemplates {
	return predicate.MailTemplates(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.MailTemplates {
	return predicate.MailTemplates(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.MailTemplates {
	return predicate.MailTemplates(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.MailTemplates {
	return predicate.MailTemplates(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.MailTemplates {
	return predicate.MailTemplates(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.MailTemplates {
	return predicate.MailTemplates(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.MailTemplates {
	return predicate.MailTemplates(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.MailTemplates {
	return predicate.MailTemplates(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.MailTemplates {
	return predicate.MailTemplates(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.MailTemplates {
	return predicate.MailTemplates(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.MailTemplates {
	return predicate.MailTemplates(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.MailTemplates {
	return predicate.MailTemplates(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.MailTemplates {
	return predicate.MailTemplates(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.MailTemplates {
	return predicate.MailTemplates(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.MailTemplates {
	return predicate.MailTemplates(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.MailTemplates {
	return predicate.MailTemplates(sql.FieldNotNull(FieldDeletedAt))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.MailTemplates {
	return predicate.MailTemplates(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.MailTemplates {
	return predicate.MailTemplates(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.MailTemplates {
	return predicate.MailTemplates(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.MailTemplates {
	return predicate.MailTemplates(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.MailTemplates {
	return predicate.MailTemplates(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.MailTemplates {
	return predicate.MailTemplates(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.MailTemplates {
	return predicate.MailTemplates(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.MailTemplates {
	return predicate.MailTemplates(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.MailTemplates {
	return predicate.MailTemplates(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.MailTemplates {
	return predicate.MailTemplates(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.MailTemplates {
	return predicate.MailTemplates(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.MailTemplates {
	return predicate.MailTemplates(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.MailTemplates {
	return predicate.MailTemplates(sql.FieldContainsFold(FieldName, v))
}

// SubjectEQ applies the EQ predicate on the "subject" field.
func SubjectEQ(v string) predicate.MailTemplates {
	return predicate.MailTemplates(sql.FieldEQ(FieldSubject, v))
}

// SubjectNEQ applies the NEQ predicate on the "subject" field.
func SubjectNEQ(v string) predicate.MailTemplates {
	return predicate.MailTemplates(sql.FieldNEQ(FieldSubject, v))
}

// SubjectIn applies the In predicate on the "subject" field.
func SubjectIn(vs ...string) predicate.MailTemplates {
	return predicate.MailTemplates(sql.FieldIn(FieldSubject, vs...))
}

// SubjectNotIn applies the NotIn predicate on the "subject" field.
func SubjectNotIn(vs ...string) predicate.MailTemplates {
	return predicate.MailTemplates(sql.FieldNotIn(FieldSubject, vs...))
}

// SubjectGT applies the GT predicate on the "subject" field.
func SubjectGT(v string) predicate.MailTemplates {
	return predicate.MailTemplates(sql.FieldGT(FieldSubject, v))
}

// SubjectGTE applies the GTE predicate on the "subject" field.
func SubjectGTE(v string) predicate.MailTemplates {
	return predicate.MailTemplates(sql.FieldGTE(FieldSubject, v))
}

// SubjectLT applies the LT predicate on the "subject" field.
func SubjectLT(v string) predicate.MailTemplates {
	return predicate.MailTemplates(sql.FieldLT(FieldSubject, v))
}

// SubjectLTE applies the LTE predicate on the "subject" field.
func SubjectLTE(v string) predicate.MailTemplates {
	return predicate.MailTemplates(sql.FieldLTE(FieldSubject, v))
}

// SubjectContains applies the Contains predicate on the "subject" field.
func SubjectContains(v string) predicate.MailTemplates {
	return predicate.MailTemplates(sql.FieldContains(FieldSubject, v))
}

// SubjectHasPrefix applies the HasPrefix predicate on the "subject" field.
func SubjectHasPrefix(v string) predicate.MailTemplates {
	return predicate.MailTemplates(sql.FieldHasPrefix(FieldSubject, v))
}

// SubjectHasSuffix applies the HasSuffix predicate on the "subject" field.
func SubjectHasSuffix(v string) predicate.MailTemplates {
	return predicate.MailTemplates(sql.FieldHasSuffix(FieldSubject, v))
}

// SubjectEqualFold applies the EqualFold predicate on the "subject" field.
func SubjectEqualFold(v string) predicate.MailTemplates {
	return predicate.MailTemplates(sql.FieldEqualFold(FieldSubject, v))
}

// SubjectContainsFold applies the ContainsFold predicate on the "subject" field.
func SubjectContainsFold(v string) predicate.MailTemplates {
	return predicate.MailTemplates(sql.FieldContainsFold(FieldSubject, v))
}

// BodyEQ applies the EQ predicate on the "body" field.
func BodyEQ(v string) predicate.MailTemplates {
	return predicate.MailTemplates(sql.FieldEQ(FieldBody, v))
}

// BodyNEQ applies the NEQ predicate on the "body" field.
func BodyNEQ(v string) predicate.MailTemplates {
	return predicate.MailTemplates(sql.FieldNEQ(FieldBody, v))
}

// BodyIn applies the In predicate on the "body" field.
func BodyIn(vs ...string) predicate.MailTemplates {
	return predicate.MailTemplates(sql.FieldIn(FieldBody, vs...))
}

// BodyNotIn applies the NotIn predicate on the "body" field.
func BodyNotIn(vs ...string) predicate.MailTemplates {
	return predicate.MailTemplates(sql.FieldNotIn(FieldBody, vs...))
}

// BodyGT applies the GT predicate on the "body" field.
func BodyGT(v string) predicate.MailTemplates {
	return predicate.MailTemplates(sql.FieldGT(FieldBody, v))
}

// BodyGTE applies the GTE predicate on the "body" field.
func BodyGTE(v string) predicate.MailTemplates {
	return predicate.MailTemplates(sql.FieldGTE(FieldBody, v))
}

// BodyLT applies the LT predicate on the "body" field.
func BodyLT(v string) predicate.MailTemplates {
	return predicate.MailTemplates(sql.FieldLT(FieldBody, v))
}

// BodyLTE applies the LTE predicate on the "body" field.
func BodyLTE(v string) predicate.MailTemplates {
	return predicate.MailTemplates(sql.FieldLTE(FieldBody, v))
}

// BodyContains applies the Contains predicate on the "body" field.
func BodyContains(v string) predicate.MailTemplates {
	return predicate.MailTemplates(sql.FieldContains(FieldBody, v))
}

// BodyHasPrefix applies the HasPrefix predicate on the "body" field.
func BodyHasPrefix(v string) predicate.MailTemplates {
	return predicate.MailTemplates(sql.FieldHasPrefix(FieldBody, v))
}

// BodyHasSuffix applies the HasSuffix predicate on the "body" field.
func BodyHasSuffix(v string) predicate.MailTemplates {
	return predicate.MailTemplates(sql.FieldHasSuffix(FieldBody, v))
}

// BodyEqualFold applies the EqualFold predicate on the "body" field.
func BodyEqualFold(v string) predicate.MailTemplates {
	return predicate.MailTemplates(sql.FieldEqualFold(FieldBody, v))
}

// BodyContainsFold applies the ContainsFold predicate on the "body" field.
func BodyContainsFold(v string) predicate.MailTemplates {
	return predicate.MailTemplates(sql.FieldContainsFold(FieldBody, v))
}

// VariablesIsNil applies the IsNil predicate on the "variables" field.
func VariablesIsNil() predicate.MailTemplates {
	return predicate.MailTemplates(sql.FieldIsNull(FieldVariables))
}

// VariablesNotNil applies the NotNil predicate on the "variables" field.
func VariablesNotNil() predicate.MailTemplates {
	return predicate.MailTemplates(sql.FieldNotNull(FieldVariables))
}

// UniqueKeyEQ applies the EQ predicate on the "unique_key" field.
func UniqueKeyEQ(v string) predicate.MailTemplates {
	return predicate.MailTemplates(sql.FieldEQ(FieldUniqueKey, v))
}

// UniqueKeyNEQ applies the NEQ predicate on the "unique_key" field.
func UniqueKeyNEQ(v string) predicate.MailTemplates {
	return predicate.MailTemplates(sql.FieldNEQ(FieldUniqueKey, v))
}

// UniqueKeyIn applies the In predicate on the "unique_key" field.
func UniqueKeyIn(vs ...string) predicate.MailTemplates {
	return predicate.MailTemplates(sql.FieldIn(FieldUniqueKey, vs...))
}

// UniqueKeyNotIn applies the NotIn predicate on the "unique_key" field.
func UniqueKeyNotIn(vs ...string) predicate.MailTemplates {
	return predicate.MailTemplates(sql.FieldNotIn(FieldUniqueKey, vs...))
}

// UniqueKeyGT applies the GT predicate on the "unique_key" field.
func UniqueKeyGT(v string) predicate.MailTemplates {
	return predicate.MailTemplates(sql.FieldGT(FieldUniqueKey, v))
}

// UniqueKeyGTE applies the GTE predicate on the "unique_key" field.
func UniqueKeyGTE(v string) predicate.MailTemplates {
	return predicate.MailTemplates(sql.FieldGTE(FieldUniqueKey, v))
}

// UniqueKeyLT applies the LT predicate on the "unique_key" field.
func UniqueKeyLT(v string) predicate.MailTemplates {
	return predicate.MailTemplates(sql.FieldLT(FieldUniqueKey, v))
}

// UniqueKeyLTE applies the LTE predicate on the "unique_key" field.
func UniqueKeyLTE(v string) predicate.MailTemplates {
	return predicate.MailTemplates(sql.FieldLTE(FieldUniqueKey, v))
}

// UniqueKeyContains applies the Contains predicate on the "unique_key" field.
func UniqueKeyContains(v string) predicate.MailTemplates {
	return predicate.MailTemplates(sql.FieldContains(FieldUniqueKey, v))
}

// UniqueKeyHasPrefix applies the HasPrefix predicate on the "unique_key" field.
func UniqueKeyHasPrefix(v string) predicate.MailTemplates {
	return predicate.MailTemplates(sql.FieldHasPrefix(FieldUniqueKey, v))
}

// UniqueKeyHasSuffix applies the HasSuffix predicate on the "unique_key" field.
func UniqueKeyHasSuffix(v string) predicate.MailTemplates {
	return predicate.MailTemplates(sql.FieldHasSuffix(FieldUniqueKey, v))
}

// UniqueKeyEqualFold applies the EqualFold predicate on the "unique_key" field.
func UniqueKeyEqualFold(v string) predicate.MailTemplates {
	return predicate.MailTemplates(sql.FieldEqualFold(FieldUniqueKey, v))
}

// UniqueKeyContainsFold applies the ContainsFold predicate on the "unique_key" field.
func UniqueKeyContainsFold(v string) predicate.MailTemplates {
	return predicate.MailTemplates(sql.FieldContainsFold(FieldUniqueKey, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.MailTemplates) predicate.MailTemplates {
	return predicate.MailTemplates(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.MailTemplates) predicate.MailTemplates {
	return predicate.MailTemplates(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.MailTemplates) predicate.MailTemplates {
	return predicate.MailTemplates(sql.NotPredicates(p))
}
